name: Lint, Format, and Push to Hugging Face

on:
  push:
    branches: [main, nosql]
  pull_request:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with pylint
        run: make lint

      - name: Format with black
        run: make format

  push-to-huggingface:
    needs: lint-and-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Git
        run: sudo apt-get install git -y

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git clone https://huggingface.co/spaces/Nishauri/ClinicianAsssitant hf-space
          rsync -av --exclude='.git' ./ hf-space/
          cd hf-space
          git add .
          git commit -m "Update Gradio app" || echo "No changes to commit"
          git push https://$HF_TOKEN@huggingface.co/spaces/Nishauri/ClinicianAsssitant main
