name: Lint, Format, and Push to Hugging Face

on:
  push:
    branches: [main, nosql]
  pull_request:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with pylint
        run: make lint

      - name: Format with black
        run: make format

  push-to-huggingface:
    needs: lint-and-format
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install huggingface_hub
        run: pip install huggingface_hub

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          huggingface-cli repo create clinician-assistant-lg --type=space --yes || true
          huggingface-cli repo upload clinician-assistant-lg . --include="*" --token $HF_TOKEN --yes
