name: Lint, Format, and Push to Hugging Face

on:
  push:
    branches: [main, nosql]
  pull_request:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with pylint
        run: make lint

      - name: Format with black
        run: make format

  push-to-huggingface:
    needs: lint-and-format
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Upgrade huggingface_hub
        run: pip install --upgrade huggingface_hub

      - name: Set up git for Hugging Face
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create Hugging Face Space (if needed)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          huggingface-cli repo create clinician-assistant-lg --type=space --space-sdk gradio --yes || true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git init
          git remote add hf https://huggingface_hub:${HF_TOKEN}@huggingface.co/spaces/Nishauri/clinician-assistant-lg
          git add .
          git commit -m "Update Space" || echo "Nothing to commit"
          git push hf main --force
