name: Lint, Format, and Push to Hugging Face

on:
  push:
    branches: [main, nosql]
  pull_request:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with pylint
        run: make lint

      - name: Format with black
        run: make format

  push-to-huggingface:
    needs: lint-and-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Avoid shallow clone

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
      - name: Push to Hugging Face
        run: |
          git remote add hf https://USERNAME:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Nishauri/ClinicianAssistant
          git push hf main --force
          git commit -m "Update Gradio app" || echo "No changes to commit"
          git push 
